/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rawat_inap.main;

import rawat_inap.entity.Dokter;
import rawat_inap.entity.LaporanInap;
import rawat_inap.entity.Pasien;
import rawat_inap.entity.Perawat;
import rawat_inap.entity.Ruangan;
import rawat_inap.entity.ConvertClassToObject;
import rawat_inap.exec.ExecuteInap;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import rawat_inap.main.BuatLaporan;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahas
 */
public class MainInap extends javax.swing.JFrame {


    /**
     * Creates new form MainFormStore
     */
    //DefaultTableModel model;
    String a1;
    
    public MainInap() {
        initComponents();
        setDataLaporan(); //Laporan
        setDataPasien(); //Pasien
        setDataRuangan(); //Ruangan
        setDataPerawat();
        setDataDokter();
    }

    public String getId(){
        return txtLaporan.getText();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setDataLaporan(){
        ConvertClassToObject cbto1 = new ConvertClassToObject();
        String[][] dataLaporan = cbto1.getAllLaporanInap();
        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            dataLaporan,
            new String [] {
                "ID LAPORAN", "ID PASIEN", "ID DOKTER", "ID PERAWAT", "ID RUANGAN", "TANGGAL INAP", "RINCIAN INAP"
            }
        ));
        jScrollPane2.setViewportView(tblLaporan);
    }

    private void setDataPasien(){
        ConvertClassToObject cbto2 = new ConvertClassToObject();
        String[][] dataPasien = cbto2.getAllPasien();
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            dataPasien,
            new String [] {
                "ID", "NAMA", "ALAMAT", "TANGGAL LAHIR", "NO. TELP", "GOL. DARAH", "KETERANGAN"
            }
        ));
        jScrollPane4.setViewportView(tblPasien);
    }    
    
    private void setDataPerawat(){
        ConvertClassToObject cbto2 = new ConvertClassToObject();
        String[][] dataPerawat = cbto2.getAllPerawat();
        tblPerawat.setModel(new javax.swing.table.DefaultTableModel(
            dataPerawat,
            new String [] {
                "ID", "NAMA", "ALAMAT", "TANGGAL LAHIR", "NO. TELP"
            }
        ));
        jScrollPane7.setViewportView(tblPerawat);
    }    
    
    private void setDataDokter(){
        ConvertClassToObject cbto2 = new ConvertClassToObject();
        String[][] dataDokter = cbto2.getAllDokter();
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            dataDokter,
            new String [] {
                "ID", "NAMA", "ALAMAT", "TANGGAL LAHIR", "NO. TELP", "KETERANGAN"
            }
        ));
        jScrollPane8.setViewportView(tblDokter);
    }    
    
    private void setDataRuangan(){
        ConvertClassToObject cbto3 = new ConvertClassToObject();
        String[][] dataRuangan = cbto3.getAllRuangan();
        tblRuangan.setModel(new javax.swing.table.DefaultTableModel(
            dataRuangan,
            new String [] {
                "ID", "KONDISI", "KELAS"
            }
        ));
        jScrollPane6.setViewportView(tblRuangan);
    }
        
    public void InsertLap(){
        setDataLaporan();
    }
    
    public void UpdateKosong(String isi){
        rawat_inap.exec.ExecuteInap eBook = new rawat_inap.exec.ExecuteInap();
        int hasil2 = eBook.updateRuanganToKosong(isi);
            if(hasil2 >0){
                JOptionPane.showMessageDialog(null, "Ruangan "+isi+" Kosong.");
                setDataRuangan();
            }
            else{
                JOptionPane.showMessageDialog(null, "Data gagal di hapus");
            }
    }
    
    public void UpdateIsi(String isi){
        rawat_inap.exec.ExecuteInap eBook = new rawat_inap.exec.ExecuteInap();
        int hasil2 = eBook.updateRuanganToIsi(isi);
            if(hasil2 >0){
                JOptionPane.showMessageDialog(null, "Ruangan "+isi+" Terisi.");
                setDataRuangan();
            }
            else{
                JOptionPane.showMessageDialog(null, "Data gagal di hapus");
            }
    }
    

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnLaporan = new javax.swing.JButton();
        btnPasien = new javax.swing.JButton();
        btnRuangan = new javax.swing.JButton();
        btnTenagaMedis = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlLaporan = new javax.swing.JPanel();
        pnlTblLaporan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        btnBuat = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtLaporan = new javax.swing.JTextField();
        txtRuangan = new javax.swing.JTextField();
        txtPasien = new javax.swing.JTextField();
        txtDokter = new javax.swing.JTextField();
        txtPerawat = new javax.swing.JTextField();
        txtRincian = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        pnlRuangan = new javax.swing.JPanel();
        pnlTblRuangan = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRuangan = new javax.swing.JTable();
        pnlTenagaMedis = new javax.swing.JPanel();
        pnlTblTenagaMedis = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPerawat = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlPasien = new javax.swing.JPanel();
        pnlTblPasien = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAWAT INAP");
        setBackground(new java.awt.Color(160, 63, 65));
        setResizable(false);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rawat_inap/icon/report2.png"))); // NOI18N
        btnLaporan.setText("LAPORAN");
        btnLaporan.setFocusable(false);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLaporan);

        btnPasien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rawat_inap/icon/patient.png"))); // NOI18N
        btnPasien.setText("PASIEN");
        btnPasien.setFocusable(false);
        btnPasien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPasien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPasien);

        btnRuangan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rawat_inap/icon/ward3.png"))); // NOI18N
        btnRuangan.setText("RUANGAN");
        btnRuangan.setFocusable(false);
        btnRuangan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRuangan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuanganActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRuangan);

        btnTenagaMedis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTenagaMedis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rawat_inap/icon/nurse2.png"))); // NOI18N
        btnTenagaMedis.setText("TENAGA MEDIS");
        btnTenagaMedis.setFocusable(false);
        btnTenagaMedis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTenagaMedis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTenagaMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenagaMedisActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTenagaMedis);

        pnlUtama.setLayout(new java.awt.CardLayout());

        tblLaporan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaporanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLaporan);

        btnBuat.setBackground(new java.awt.Color(51, 153, 0));
        btnBuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuat.setForeground(new java.awt.Color(0, 0, 0));
        btnBuat.setText("BUAT LAPORAN");
        btnBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE LAPORAN");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(153, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setText("HAPUS LAPORAN");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTblLaporanLayout = new javax.swing.GroupLayout(pnlTblLaporan);
        pnlTblLaporan.setLayout(pnlTblLaporanLayout);
        pnlTblLaporanLayout.setHorizontalGroup(
            pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                        .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                                .addComponent(txtLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                                .addComponent(txtDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPerawat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRincian, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlTblLaporanLayout.setVerticalGroup(
            pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblLaporanLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuat)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTblLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPerawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRincian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLaporanLayout = new javax.swing.GroupLayout(pnlLaporan);
        pnlLaporan.setLayout(pnlLaporanLayout);
        pnlLaporanLayout.setHorizontalGroup(
            pnlLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTblLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLaporanLayout.setVerticalGroup(
            pnlLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlTblLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlLaporan, "cardLaporan");

        tblRuangan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRuanganMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblRuangan);
        if (tblRuangan.getColumnModel().getColumnCount() > 0) {
            tblRuangan.getColumnModel().getColumn(0).setResizable(false);
            tblRuangan.getColumnModel().getColumn(1).setResizable(false);
            tblRuangan.getColumnModel().getColumn(2).setResizable(false);
            tblRuangan.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlTblRuanganLayout = new javax.swing.GroupLayout(pnlTblRuangan);
        pnlTblRuangan.setLayout(pnlTblRuanganLayout);
        pnlTblRuanganLayout.setHorizontalGroup(
            pnlTblRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblRuanganLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblRuanganLayout.setVerticalGroup(
            pnlTblRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRuanganLayout = new javax.swing.GroupLayout(pnlRuangan);
        pnlRuangan.setLayout(pnlRuanganLayout);
        pnlRuanganLayout.setHorizontalGroup(
            pnlRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTblRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRuanganLayout.setVerticalGroup(
            pnlRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTblRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pnlUtama.add(pnlRuangan, "cardRuangan");

        tblPerawat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPerawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerawatMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblPerawat);
        if (tblPerawat.getColumnModel().getColumnCount() > 0) {
            tblPerawat.getColumnModel().getColumn(0).setResizable(false);
            tblPerawat.getColumnModel().getColumn(1).setResizable(false);
            tblPerawat.getColumnModel().getColumn(2).setResizable(false);
            tblPerawat.getColumnModel().getColumn(3).setResizable(false);
        }

        tblDokter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokterMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblDokter);
        if (tblDokter.getColumnModel().getColumnCount() > 0) {
            tblDokter.getColumnModel().getColumn(0).setResizable(false);
            tblDokter.getColumnModel().getColumn(1).setResizable(false);
            tblDokter.getColumnModel().getColumn(2).setResizable(false);
            tblDokter.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("DOKTER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PERAWAT");

        javax.swing.GroupLayout pnlTblTenagaMedisLayout = new javax.swing.GroupLayout(pnlTblTenagaMedis);
        pnlTblTenagaMedis.setLayout(pnlTblTenagaMedisLayout);
        pnlTblTenagaMedisLayout.setHorizontalGroup(
            pnlTblTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblTenagaMedisLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlTblTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(pnlTblTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                        .addComponent(jScrollPane8)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlTblTenagaMedisLayout.setVerticalGroup(
            pnlTblTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblTenagaMedisLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pnlTenagaMedisLayout = new javax.swing.GroupLayout(pnlTenagaMedis);
        pnlTenagaMedis.setLayout(pnlTenagaMedisLayout);
        pnlTenagaMedisLayout.setHorizontalGroup(
            pnlTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTenagaMedisLayout.createSequentialGroup()
                .addComponent(pnlTblTenagaMedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        pnlTenagaMedisLayout.setVerticalGroup(
            pnlTenagaMedisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTenagaMedisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTblTenagaMedis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pnlUtama.add(pnlTenagaMedis, "cardTenagaMedis");

        tblPasien.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPasien);
        if (tblPasien.getColumnModel().getColumnCount() > 0) {
            tblPasien.getColumnModel().getColumn(0).setResizable(false);
            tblPasien.getColumnModel().getColumn(1).setResizable(false);
            tblPasien.getColumnModel().getColumn(2).setResizable(false);
            tblPasien.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlTblPasienLayout = new javax.swing.GroupLayout(pnlTblPasien);
        pnlTblPasien.setLayout(pnlTblPasienLayout);
        pnlTblPasienLayout.setHorizontalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblPasienLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblPasienLayout.setVerticalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPasienLayout = new javax.swing.GroupLayout(pnlPasien);
        pnlPasien.setLayout(pnlPasienLayout);
        pnlPasienLayout.setHorizontalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addComponent(pnlTblPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        pnlPasienLayout.setVerticalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTblPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pnlUtama.add(pnlPasien, "cardPasien");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("SISTEM RAWAT INAP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardLaporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasienActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPasien");
    }//GEN-LAST:event_btnPasienActionPerformed

    private void btnRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuanganActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardRuangan");
    }//GEN-LAST:event_btnRuanganActionPerformed

    private void tblLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaporanMouseClicked
        // TODO add your handling code here:
        btnHapus.setEnabled(true);
        btnUpdate.setEnabled(true);
        int row = tblLaporan.getSelectedRow();
        
        String idlaporan = tblLaporan.getValueAt(row, 0).toString();
        String idpasien = tblLaporan.getValueAt(row, 1).toString();
        String iddokter = tblLaporan.getValueAt(row, 2).toString();
        String idperawat = tblLaporan.getValueAt(row, 3).toString();
        String idruangan = tblLaporan.getValueAt(row, 4).toString();
        String tanggal = tblLaporan.getValueAt(row, 5).toString();
        String rincian = tblLaporan.getValueAt(row, 6).toString();
        
        txtLaporan.setText(idlaporan);
        txtRuangan.setText(idruangan);
        txtPasien.setText(idpasien);
        txtDokter.setText(iddokter);
        txtPerawat.setText(idperawat);
        txtTanggal.setText(tanggal);
        txtRincian.setText(rincian);
        
    }//GEN-LAST:event_tblLaporanMouseClicked

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPasienMouseClicked

    private void tblRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRuanganMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRuanganMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        MainInap ma = new MainInap();
        UpdateLaporan ulap = new UpdateLaporan();
        new UpdateLaporan(txtLaporan.getText(), txtPasien.getText(), txtDokter.getText(),txtPerawat.getText(), txtRuangan.getText(), txtRincian.getText()).setVisible(true);
        //new UpdateLaporan
        //getId();
        //ulap.PreData();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatActionPerformed
        // TODO add your handling code here:
        MainInap ma = new MainInap();
        BuatLaporan blap = new BuatLaporan();
        blap.setVisible(true);
        
    }//GEN-LAST:event_btnBuatActionPerformed

    private void tblPerawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerawatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPerawatMouseClicked

    private void tblDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDokterMouseClicked

    private void btnTenagaMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenagaMedisActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardTenagaMedis");
    }//GEN-LAST:event_btnTenagaMedisActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String strkode = txtLaporan.getText();
        String strruangan = txtRuangan.getText();
        rawat_inap.exec.ExecuteInap eBook = new rawat_inap.exec.ExecuteInap();
        int hasil = eBook.deleteLaporan(strkode);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Laporan berhasil di hapus");
            setDataLaporan();
            int hasil2 = eBook.updateRuanganToKosong(strruangan);
            if(hasil2 >0){
                JOptionPane.showMessageDialog(null, "Ruangan "+strruangan+" Kosong.");
                setDataRuangan();
            }
            else{
                JOptionPane.showMessageDialog(null, "Data gagal di hapus");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        setDataLaporan(); //Laporan
        setDataPasien(); //Pasien
        setDataRuangan(); //Ruangan
        setDataPerawat();
        setDataDokter();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInap().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuat;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnPasien;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRuangan;
    private javax.swing.JButton btnTenagaMedis;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlLaporan;
    private javax.swing.JPanel pnlPasien;
    private javax.swing.JPanel pnlRuangan;
    private javax.swing.JPanel pnlTblLaporan;
    private javax.swing.JPanel pnlTblPasien;
    private javax.swing.JPanel pnlTblRuangan;
    private javax.swing.JPanel pnlTblTenagaMedis;
    private javax.swing.JPanel pnlTenagaMedis;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblDokter;
    public javax.swing.JTable tblLaporan;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTable tblPerawat;
    private javax.swing.JTable tblRuangan;
    private javax.swing.JTextField txtDokter;
    public javax.swing.JTextField txtLaporan;
    private javax.swing.JTextField txtPasien;
    private javax.swing.JTextField txtPerawat;
    private javax.swing.JTextField txtRincian;
    private javax.swing.JTextField txtRuangan;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
